- name: Install docker and run nginx image
  hosts: server
  become: True
  vars:
    user_home: /home/ec2-user
    server_home: /home/ec2-user
  tasks:
    - name: Install docker on amazon linux 2
      ansible.builtin.yum:
        name:
          - docker
          - python3-requests
        state: present

    - name: Start docker service
      service:
        name: docker
        state: started

    - name: Enable docker service
      service:
         name: docker
         enabled: yes

    - name: Starting Docker Containers
      docker_container:
        name: nginx
        image: bkt92/hello-nginx
        published_ports: 80:80
        state: started
